version: '3'
services:
  opencensus:
    build: .
    ports:
     - "9999:9999"
  prometheus:
    image: "prom/prometheus"
    ports:
     - "9090:9090"
    volumes:
     - prometheusetc:/etc/prometheus
volumes:
  prometheusetc: {}
